const EN = {
  app_name: 'Rabiloo Hamic',
  sign_in: 'Sign in',
  sign_in_successful: 'Login successfully',
  sign_up_successful: 'Sign up successfully',
  email: 'Email',
  password: 'Password',
  remember_me: 'Remember me',
  forgot_password: 'Forgot password?',
  dont_have_account: "Don't have an account? Sign Up",
  develop_by: 'developed by',
  english: 'English',
  vietnamese: 'Vietnamese',
  phone: 'Phone',
  age: 'Age',
  detail: 'Detail',
  users: 'Users',
  cancel: 'Cancel',
  confirm: 'Confirm',
  logout: 'Logout',
  home: 'Home',
  do_you_wanna_logout: 'Do you want to logout?',
  sign_up: 'Sign Up',
  first_name: 'First Name',
  last_name: 'Last Name',
  password_confirm: 'Confirm password',
  accept_term: 'I accept the Term of Use & Privacy Policy.',
  accept_receive_email: 'I accept to receive email.',
  city: 'City',
  dob: 'Birth',
  gender: 'Gender',
  honorific: 'Honorific',
  male: 'Male',
  female: 'Female',
  other: 'Other',
  already_have_account: 'Already have an account? Sign in.',
  doy_you_wanna_delete_this: e => 'Do you want to delete ' + e + '?',

  this_field_is_required: 'This field is required',
  email_is_not_valid: 'Email is not valid',
  password_invalid:
    'Password must contain at least 8 characters, uppercase, lowercase and number',
  is_not_same_password: 'Confirm password is not correct',
  continue_reading: 'Continue reading…',
  archives: 'Archives',
  social: 'Socical',
  about: 'About',
  add_user: 'Add user',
  edit_user: 'Edit user',
  name: 'Name',
  date_is_invalid: 'Date is invalid',
  add_success_common: 'Added successfully',
  edit_success_common: 'Edited successfully',
  deleted_success_common: 'Deleted successfully',
  do_you_wanna_delete_user: 'Do you want to delete user?',
  pl_table: 'Submission History',
  user_info: 'User Info',
  update: 'Update',
  // time: "Time",
  // date: "Date",
  // score: "Score",
  problem: 'Problem',
  status: 'Status',
  question: 'Question',
  exam: 'Exam',
  sign_in_failed: 'Login failed, wrong account',
  name_question: 'Name question',
  one_answer: 'One answer',
  many_answer: 'Many answer',
  text_answer: 'Text answer',
  name_test: 'Name test',
  desc_test: 'Descriptions test',
  code_test: 'Code test',
  submit: 'Submit',
  edit: 'Edit',
  delete: 'Delete',
  start: 'Start',
  edit_modal: 'Edit Modal',
  update_test: 'Update Test',
  congrats: 'Congratulation',
  score: 'Your score',
  right_answer: 'Number of right answers',
};

const VI = {
  ...EN,
  app_name: 'Rabiloo Hamic',
  sign_in: 'Đăng nhập',
  sign_in_successful: 'Đăng nhập thành công',
  sign_up_successful: 'Đăng ký thành công',
  email: 'Email',
  password: 'Mật khẩu',
  remember_me: 'Nhớ tài khoản',
  forgot_password: 'Quên mật khẩu?',
  dont_have_account: 'Bạn chưa có tài khoản? Đăng ký',
  develop_by: 'được phát triển bởi',
  english: 'Tiếng Anh',
  vietnamese: 'Tiếng Việt',
  phone: 'Số điện thoại',
  age: 'Tuổi',
  detail: 'Xem Chi tiết',
  users: 'Người dùng',
  cancel: 'Hủy',
  confirm: 'Xác nhận',
  logout: 'Đăng xuất',
  home: 'Trang chủ',
  do_you_wanna_logout: 'Bạn có muốn đăng xuất không?',
  sign_up: 'Đăng ký',
  first_name: 'Họ',
  last_name: 'Tên',
  password_confirm: 'Xác nhận mật khẩu',
  accept_term: 'Đồng ý với điều khoản và chính sách bảo mật',
  accept_receive_email: 'Đồng ý nhận Email',
  city: 'Thành phố',
  dob: 'Ngày sinh',
  gender: 'Giới tính',
  honorific: 'Kính ngữ',
  male: 'Nam',
  female: 'Nữ',
  other: 'Khác',
  already_have_account: 'Đã có tài khoản? Đăng nhập.',
  doy_you_wanna_delete_this: e => 'Bạn có muốn xóa ' + e + ' không?',

  this_field_is_required: 'Trường này là bắt buộc',
  email_is_not_valid: 'Email không hợp lệ',
  password_invalid: 'Mật khẩu phải bao gồm 8 ký tự, chữ hoa, chữ thường và số',
  is_not_same_password: 'Mật khẩu xác nhận không đúng',
  continue_reading: 'Đọc tiếp…',
  archives: 'Kho lưu trữ',
  social: 'Mạng xã hội',
  about: 'Về chúng tôi',
  add_user: 'Thêm người dùng',
  edit_user: 'Chỉnh sửa',
  name: 'Tên',
  date_is_invalid: 'Sai định dạng ngày',
  add_success_common: 'Thêm mới thành công',
  edit_success_common: 'Chỉnh sửa thành công',
  deleted_success_common: 'Xóa thành công',
  do_you_wanna_delete_user: 'Bạn có muốn xóa người dùng không?',
  pl_table: 'Lịch sử nộp bài',
  user_info: 'Thông tin người dùng',
  update: 'Cập nhật',
  question: 'Question',
  // time: "Thời gian làm bài",
  // date: "Nộp bài lúc",
  // score: "Điểm số",
  problem: 'Danh sách bài thi',
  status: 'Thông báo',
  question: 'Câu hỏi',

  exam: 'Bài thi',
  sign_in_failed: 'Đăng nhập không thành công, sai tài khoản hoặc mật khẩu',
  name_question: 'Câu hỏi',
  one_answer: 'Một đáp án',
  many_answer: 'Nhiều đáp án',
  text_answer: 'Nhập đáp án',
  name_test: 'Tên bài thi',
  desc_test: 'Mô tả bài thi',
  code_test: 'Code bài thi',
  submit: 'Hoàn Thành',
  edit: 'Sửa',
  delete: 'Xoá',
  start: 'Start',
  edit_modal: 'Sửa Modal',
  update_test: 'Sửa Bài',
  congrats: 'Chúc mừng bạn đã hoàn thành bài thi',
  score: 'Điểm của bạn là',
  right_answer: 'Số câu trả lời đúng',
};

const JP = {
  ...EN,
};

const Strings = {
  EN: EN,
  VI: VI,
  JP: JP,
};

export {Strings};
